# **Python Basics**
___
___

### Topics


*   Class Object
*   **`lamda function`**
*   **`List Comprehension`**
*   Numpy
*   List Comprehension
*   Indexing / Slicing

**Class Object**

In [1]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


**lamda function**

In [2]:
my_function = lambda a, b, c : a + b
my_function(1, 2, 3)

3

**List Comprehension**

In [5]:
my_list = [number for number in range(0,10) if number % 2 == 0]
my_list

[0, 2, 4, 6, 8]

In [27]:
lowercase = 'abcdef'
digits = '123456'

lists = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]
print(lists)

['aa11', 'aa12', 'aa13', 'aa14', 'aa15', 'aa16', 'aa21', 'aa22', 'aa23', 'aa24', 'aa25', 'aa26', 'aa31', 'aa32', 'aa33', 'aa34', 'aa35', 'aa36', 'aa41', 'aa42', 'aa43', 'aa44', 'aa45', 'aa46', 'aa51', 'aa52', 'aa53', 'aa54', 'aa55', 'aa56', 'aa61', 'aa62', 'aa63', 'aa64', 'aa65', 'aa66', 'ab11', 'ab12', 'ab13', 'ab14', 'ab15', 'ab16', 'ab21', 'ab22', 'ab23', 'ab24', 'ab25', 'ab26', 'ab31', 'ab32', 'ab33', 'ab34', 'ab35', 'ab36', 'ab41', 'ab42', 'ab43', 'ab44', 'ab45', 'ab46', 'ab51', 'ab52', 'ab53', 'ab54', 'ab55', 'ab56', 'ab61', 'ab62', 'ab63', 'ab64', 'ab65', 'ab66', 'ac11', 'ac12', 'ac13', 'ac14', 'ac15', 'ac16', 'ac21', 'ac22', 'ac23', 'ac24', 'ac25', 'ac26', 'ac31', 'ac32', 'ac33', 'ac34', 'ac35', 'ac36', 'ac41', 'ac42', 'ac43', 'ac44', 'ac45', 'ac46', 'ac51', 'ac52', 'ac53', 'ac54', 'ac55', 'ac56', 'ac61', 'ac62', 'ac63', 'ac64', 'ac65', 'ac66', 'ad11', 'ad12', 'ad13', 'ad14', 'ad15', 'ad16', 'ad21', 'ad22', 'ad23', 'ad24', 'ad25', 'ad26', 'ad31', 'ad32', 'ad33', 'ad34', 'ad35',

**NumPy**

In [6]:
import numpy as np

In [7]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [8]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [9]:
m.shape

(2, 3)

In [11]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [14]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [15]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [16]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [21]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

**Indexing / Slicing**

In [23]:
s = np.arange(13)**2
s

print(s[-4:])

print(s[-5::-2])

[ 81 100 121 144]
[64 36 16  4  0]


In [24]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [25]:
r[3, 3:6]

array([21, 22, 23])